[package]
name = "tuner-core"
version.workspace = true
edition = "2024"

[dependencies]
# Use the workspace-defined versions
anyhow = "1.0.102" # For easier error handling

# For running audio on a separate thread and communicating
crossbeam-channel = { workspace = true }
ringbuf = { workspace = true }
cpal = { workspace = true }

# Add other dependencies for math, etc.
rustfft = { workspace = true }
linreg = "0.2.0"
once_cell = "1.21.3"

# For profile saving and loading
serde =  { workspace = true }
