[package]
name = "tuner-gui"
version.workspace = true
edition = "2024"

[dependencies]
# Dependency on the local core logic crate
tuner-core = { path = "../tuner-core" }

# Iced is a popular choice for GUIs in Rust
iced = { version = "0.14.0", features = ["canvas", "tokio", "advanced"] }



# For running audio on a separate thread and communicating
cpal = { workspace = true }
ringbuf = { workspace = true }
crossbeam-channel = { workspace = true }


# For profile saving and loading
serde = { workspace = true }
serde_json = { workspace = true }

anyhow = "1.0.102" # For easier error handling
rustfft.workspace = true

